import { GenerateV1Input } from "@hautechai/sdk/dist/autogenerated/api";
import { SDK } from "@hautechai/sdk";

export type GenerateWidgetIncomingMethodHandlers = {
  downloadImage: (data: { imageId: string }) => Promise<void>;
};

export type GenerateWidgetButton = {
  text?: string;
  visible?: boolean;
};

export type GenerateWidgetProps = {
  buttons?: {
    download?: GenerateWidgetButton;
    retouch?: GenerateWidgetButton;
    upscale?: GenerateWidgetButton;
  };
  collectionId: string;
  input: Partial<GenerateV1Input> & { productImageId: string; prompt: string };
};

export type GenerateWidgetOutcomingMethods = {
  getImages: () => Promise<string[]>;
  setProps: (props: GenerateWidgetProps) => Promise<void>;
  start: () => Promise<void>;
};

export type Props = {
  sdk: SDK;
  setIncomingMethodHandlers: (
    handlers: Omit<GenerateWidgetOutcomingMethods, "setProps">
  ) => void;
  widgetMethods: GenerateWidgetIncomingMethodHandlers;
  widgetProps: GenerateWidgetProps;
};
